version: "3.9"

services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: user-service

  app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: app