name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Microservices
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to the container registry
      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }} # Set this as a secret in GitHub
          password: ${{ secrets.REGISTRY_PASSWORD }} # Set this as a secret in GitHub

      # Build and push microservice1
      - name: Build and Push Microservice1
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME1 }}:${{ env.IMAGE_VERSION }} ./order-service
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME1 }}:${{ env.IMAGE_VERSION }}

      # Build and push microservice2
      - name: Build and Push Microservice2
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME2 }}:${{ env.IMAGE_VERSION }} ./user-service
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME2 }}:${{ env.IMAGE_VERSION }}
