name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies and build the front-end
      - name: Build Front-End App
        working-directory: front-end
        run: |
          yarn install --frozen-lockfile
          yarn build

      # Build and push Docker image for the front-end
      - name: Build and Push Front-End Docker Image
        working-directory: front-end
        run: |
          docker build -t your-dockerhub-username/vite-app .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/vite-app

      # Build and push Docker image for user-service
      - name: Build and Push User-Service Docker Image
        working-directory: user-service
        run: |
          docker build -t your-dockerhub-username/user-service .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/user-service

      # Build and push Docker image for order-service
      - name: Build and Push Order-Service Docker Image
        working-directory: order-service
        run: |
          docker build -t your-dockerhub-username/order-service .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/order-service
