name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  # Front-End Job
  front-end:
    name: Build and Deploy Front-End
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies and build the front-end
      - name: Install and Build Front-End
        working-directory: front-end
        run: |
          yarn install --frozen-lockfile
          yarn build

      # Build and push Docker image for the front-end
      - name: Build and Push Front-End Docker Image
        working-directory: front-end
        run: |
          docker build -t hugosoum/vite-app .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push hugosoum/vite-app

  # User-Service Job
  user-service:
    name: Build and Deploy User-Service
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build and push Docker image for user-service
      - name: Build and Push User-Service Docker Image
        working-directory: user-service
        run: |
          docker build -t hugosoum/user-service .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push hugosoum/user-service

  # Order-Service Job
  order-service:
    name: Build and Deploy Order-Service
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build and push Docker image for order-service
      - name: Build and Push Order-Service Docker Image
        working-directory: order-service
        run: |
          docker build -t hugosoum/order-service .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push hugosoum/order-service
